version: '3'
services:
  redis:
    image: "redis:alpine"
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: ["redis"]
    command: "/redis-proxy.sh"
  test:
    depends_on: ["proxy"]
    build:
      context: .
      dockerfile: Dockerfile.test
